### ISSUE TITLE
RFE: bg color for status tables

### ISSUE THREAD

**Issue by nthomas-redhat** [Tendrl/monitoring-integration#200]
Keep the green(or any based on the status val) bg colour only the status column, not the entire line with name of brick, so you avoid too much green in the dashboard.

**Comment by cloudbehl** [comment]
@nthomas-redhat I think we have implemented this as @mcarrano Suggested. So is there anything else we need to do?

**Comment by mcarrano** [comment]
@julienlim and I had discussed this and decided to keep the bg color extending across the entire row rather than just highlighting the status column. The thinking was that the status value is not really meaningful and we wanted to highlight the object name. Agree that this is not an ideal solution but seemed like the best we can do within the constraints of the Grafana table panel.

**Comment by nthomas-redhat** [comment]
Ack. Closing the issue
