### ISSUE TITLE
Some huge numbers reported by grafana are hard to read and understand

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/monitoring-integration#383]
"Weeks Remaining" probably doesn't make much sense to show
  exact numbers for more than few years (and it might make sense to recalculate
  the number of weeks to number of months or years for longer periods).

  "Inode available" as this number doesn't have any unit (to prepend it with
  k,M,G...) it might make sense to show the number in form like:
  3124138767 ~ 3.1*10^9
  or something like that.

**Comment by cloudbehl** [comment]
![brick-dashboard](https://user-images.githubusercontent.com/6695156/37653946-8b743be8-2c66-11e8-9721-0847935da34e.png)
![dashboard](https://user-images.githubusercontent.com/6695156/37653947-8bf317ce-2c66-11e8-8ec6-5e9b2793f490.png)
![volume-dashboard](https://user-images.githubusercontent.com/6695156/37653948-8c2ac8e0-2c66-11e8-9f46-8dfe203ae795.png)

**Comment by cloudbehl** [comment]
![screenshot from 2018-03-20 17-48-26](https://user-images.githubusercontent.com/6695156/37654114-095fb51e-2c67-11e8-80e3-28894b1856c5.png)

![screenshot from 2018-03-20 17-47-21](https://user-images.githubusercontent.com/6695156/37654109-09283c74-2c67-11e8-8bd5-64c6989934d6.png)


> "Inode available" as this number doesn't have any unit (to prepend it with
> k,M,G...) it might make sense to show the number in form like:
> 3124138767 ~ 3.1*10^9
> or something like that.
@dahorak @julienlim can we show the Inodes as shown in the picture(9e+6) I attached above? That's the best way I have found to show the Inode in grafana.

**Comment by julienlim** [comment]
@cloudbehl @dahorak 

I commented on this bug recently in [BZ 1549146](https://bugzilla.redhat.com/show_bug.cgi?id=1549146) on what my recommendations were.  The suggestion of showing something in the form scientific (exponential) notation, e.g. 1E+04 or 2.4 x 10^4 etc., is not preferred as it's less usable and requires users to have to think harder to convert the number in their heads.

WRT Inodes, as mentioned in the above BZ, we can probably remove the Inodes Utilization and Inodes Available panels as @mbukatov is correct in noting that inodes is less a concern for Gluster since XFS supports dynamic inode allocation.

**Comment by cloudbehl** [comment]
@r0h4n @nthomas-redhat any comments from your side?

**Comment by nthomas-redhat** [comment]
I agree with @julienlim .

Earlier there was a request from field as well as it is really doesn't make sense for the customers it seems. Based on that there was an issue raised https://github.com/Tendrl/monitoring-integration/issues/201

**Comment by cloudbehl** [comment]
@julienlim @nthomas-redhat Sure then will remove it. 

@julienlim can you provide me the UX changes that will be required after the removal of the panels.

**Comment by julienlim** [comment]
@cloudbehl @nthomas-redhat @mcarrano @Tendrl/qe 

After removing the inodes related panels, I've modified the panel layouts -- see Volume dashboard and Brick dashboard below (I made changes based on Tendrl 1.6.1 dashboards):

<img width="1266" alt="volume dashboard" src="https://user-images.githubusercontent.com/5589919/37789437-4916ff7c-2dda-11e8-9eb3-cd3e8da652cf.png">

<img width="1268" alt="brick dashboard" src="https://user-images.githubusercontent.com/5589919/37789441-4bf8142e-2dda-11e8-8500-631d6d71e089.png">

**Comment by cloudbehl** [comment]
@julienlim In volume Dashboard you have put snapshots in the capacity row, Is it snapshots part of a capacity row?

**Comment by julienlim** [comment]
@cloudbehl Snapshots should not be part of the Capacity row.  It should be part of the first row.  You might have to resize the "Rebalance" panel to take less room to have Snapshots up on the first row.

**Comment by cloudbehl** [comment]
@julienlim can you please check this if it's looking good or not?
![screenshot from 2018-03-26 21-47-27](https://user-images.githubusercontent.com/6695156/37918674-693e867c-313f-11e8-8153-b0394d8a03c7.png)

**Comment by julienlim** [comment]
@cloudbehl 
Overall looks good, but snapshots should be the last panel on the first row, and some of the ordering is not right on the first row. 

It should be: Health, Bricks, Brick Status, Subvolume, Geo-rep sessions, Rebalance, Rebalance Status, Snapshots.

**Comment by cloudbehl** [comment]
linking Inode removal Issue: https://github.com/Tendrl/monitoring-integration/issues/201

**Comment by shirshendu** [comment]
@cloudbehl Grafana dashboard for bricks is no longer loading because of a minor bug in the above merge, which causes monitoring-integration service to fail.
https://github.com/Tendrl/monitoring-integration/blob/c946f161bc17a27b3fd6f820e0eeaeda3b6adfcb/etc/tendrl/monitoring-integration/grafana/dashboards/tendrl-gluster-bricks.json#L446

I'll raise a PR for this now.
