### ISSUE TITLE
host is down, don't see it on dashboards

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/monitoring-integration#51]
I've imported cluster and after more than 30 minutes I've shut down *gl4* machine.
1) There is no alert about this and host is not marked as down in Tendrl UI.
1) Host status is not reflected also in Grafana dashboards except of one chart about number of hosts which are down.
Please see screenshots for details.

Used packages:
```
etcd-3.1.9-1.el7.x86_64
glusterfs-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-api-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-cli-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-client-xlators-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-fuse-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-libs-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-server-4.0dev-0.85.gitea48cae.el7.centos.x86_64
python-etcd-0.4.5-1.noarch
rubygem-etcd-0.3.0-1.el7.centos.noarch
tendrl-api-1.5.1-1.el7.centos.noarch
tendrl-api-httpd-1.5.1-1.el7.centos.noarch
tendrl-commons-1.5.1-1.el7.centos.noarch
tendrl-gluster-integration-1.5.1-1.el7.centos.noarch
tendrl-monitoring-integration-1.5.1-1.el7.centos.noarch
tendrl-node-agent-1.5.1-1.el7.centos.noarch
tendrl-ui-1.5.1-1.el7.centos.noarch
```
![bug_host_down1](https://user-images.githubusercontent.com/5920442/29870614-c9470bc6-8d88-11e7-960f-7dae89a19fcc.png)
![bug_host_down2](https://user-images.githubusercontent.com/5920442/29870615-c96e5046-8d88-11e7-9b0f-f48783a148a1.png)
![bug_host_down3](https://user-images.githubusercontent.com/5920442/29870616-c970986a-8d88-11e7-99ec-3cb4cb9fe03f.png)
![bug_host_down4](https://user-images.githubusercontent.com/5920442/29870617-c9711a10-8d88-11e7-9991-338b9fe71683.png)

**Comment by cloudbehl** [comment]
@mkudlej Can you check if monitoring-integration service is running on your system?

@anmolbabu can you check why the brick level utilization is not getting collected? As all other data is available. Also, @mkudlej has shut down the gl4 instance but still the graphite is pushing the data 

cc: @rishubhjain

**Comment by cloudbehl** [comment]
linking: https://github.com/Tendrl/node-agent/issues/592

**Comment by anmolbabu** [comment]
>@anmolbabu can you check why the brick level utilization is not getting collected? 

Regarding the first issue I would need to know if there are any errors in service collectd status -l
or /var/log/messages to be able to better comment on this
Cc: @mkudlej 

>As all other data is available. Also, @mkudlej has shut down the gl4 instance but still the graphite is pushing the data
No graphite doesn't push any data. Its only a time-series data store. 
1. The data is either pushed by collectd or monitoring-integration to graphite. 
2. The data in graphite is stored on disk in the form of .wsp whisper files. 
So, graphite being updated of latest stats from a node that is down is impossible if down == actually node is down(not just some processes). 
Now given the above, the stats for node gl4 is still visible on grafana because of 2 which means, the new stats are not pushed to graphite doesn't mean the old stats are deleted(The only means to delete is to actually rm the file corresponding to the metric from the path /var/lib/carbon/whisper/tendrl) which is out of reach of collectd. Also, if this was a time series graph the disconnect would have been easily noticeable by the absence of data on the graph but I believe in case of showing point in time data, grafana picks the last successfully measured non-null value in graphite over the period of last 24 hours for the metric and hence this issue

**Comment by mkudlej** [comment]
@cloudbehl Monitoring integration service is up and running.

**Comment by mkudlej** [comment]
@anmolbabu I don't see any error related to this bug in /var/log/messages

**Comment by rishubhjain** [comment]
@mkudlej Is this bug stilll reproducable?
